#ifndef DISPLAY_MACROS_H
#define DISPLAY_MACROS_H

#define DISP_FORCE_LEFT 0x80
#define DISP_FORCE_RIGHT 0x7f
#define DISP_OFF 0b1111111
#define DISP_DIGIT_ZERO 0x08
#define DISP_DIGIT_ONE 0x6b
#define DISP_DIGIT_TWO 0x44
#define DISP_DIGIT_THREE 0x41
#define DISP_DIGIT_FOUR 0x23
#define DISP_DIGIT_FIVE 0x11
#define DISP_DIGIT_SIX 0x10
#define DISP_DIGIT_SEVEN 0x4b
#define DISP_DIGIT_EIGHT 0x00
#define DISP_DIGIT_NINE 0x01

#endif
