PPQN = 24
TICKS_WHOLE = PPQN * 4
TICKS_HALF = PPQN * 2
TICKS_QUARTER = PPQN
TICKS_EIGHTH = PPQN // 2
TICKS_SIXTEENTH = PPQN // 4
TICKS_THIRTYSECOND = PPQN // 8

ARTICULATION_REGULAR = 0.9
ARTICULATION_STACCATO = 0.5

NOTE_CHAR_START_IDX = ord(':')
NOTE_CHAR_OFFSET_SHARP = 1
NOTE_CHAR_OFFSET_FLAT = 2
NOTE_CHAR_OFFSET_SYM = 3

PREFIX_FERMATA = 'f'
PREFIX_BPM = 'b'
PREFIX_ANACRUSIS = 'a'
PREFIX_TIMESIG = 't'
PREFIX_REST = '*'