# Additional constants
ADDITIONAL_DOTNOTE = '.'
ADDITIONAL_FERMATA = '@'
ADDITIONAL_SLUR_BEGIN = '<'
ADDITIONAL_SLUR_END = '>'
ADDITIONAL_STACCATO = 's'

# Break constants
BREAK_SYM = '*'
BREAKSTRUCT_EXPLEN = 2
BREAKSTRUCT_SEP = '-'

# Duration constants
DURATION_WHOLE = 1
DURATION_HALF = 2
DURATION_QUARTER = 4
DURATION_EIGHTH = 8
DURATION_SIXTEENTH = 16
DURATION_THIRTYSECOND = 32

# Note constants
NOTE_ACCIDENTAL_FLAT = 'b'
NOTE_ACCIDENTAL_SHARP = '#'
NOTE_EXPLEN_LONG = 3
NOTE_EXPLEN_SHORT = 2
NOTE_IDX_ACCIDENTAL = 1
NOTE_IDX_OCTAVE_LONG = 2
NOTE_IDX_OCTAVE_SHORT = 1
NOTE_IDX_SYMBOL = 0
NOTE_OCTAVE_MIN = 1
NOTE_OCTAVE_MAX = 8
NOTE_SEP = ' '
NOTE_SYM_A = 'A'
NOTE_SYM_B = 'B'
NOTE_SYM_C = 'C'
NOTE_SYM_D = 'D'
NOTE_SYM_E = 'E'
NOTE_SYM_F = 'F'
NOTE_SYM_G = 'G'

# Note structure constants
NOTESTRUCT_IDX_ADDITIONALS = 2
NOTESTRUCT_IDX_DURATION = 1
NOTESTRUCT_IDX_NOTE = 0
NOTESTRUCT_EXPLEN_LONG = 3
NOTESTRUCT_EXPLEN_SHORT = 2
NOTESTRUCT_SEP = '-'

# Tuplet constants
TUPLET_CLOSE = ')'
TUPLET_OPEN = '('
TUPLET_EXPDEFS = 3
TUPLET_SEP_DEF = ':'
TUPLET_SEP_NOTE = '_'

# Lists of valid values
VALID_ADDITIONALS = [
    ADDITIONAL_DOTNOTE,
    ADDITIONAL_FERMATA,
    ADDITIONAL_SLUR_BEGIN,
    ADDITIONAL_SLUR_END,
    ADDITIONAL_STACCATO
]
VALID_DURATIONS = [
    DURATION_WHOLE,
    DURATION_HALF,
    DURATION_QUARTER,
    DURATION_EIGHTH,
    DURATION_SIXTEENTH,
    DURATION_THIRTYSECOND
]
VALID_NOTESTRUCT_LENS = [
    NOTESTRUCT_EXPLEN_LONG,
    NOTESTRUCT_EXPLEN_SHORT
]
VALID_SYMS = [
    NOTE_SYM_A,
    NOTE_SYM_B,
    NOTE_SYM_C,
    NOTE_SYM_D,
    NOTE_SYM_E,
    NOTE_SYM_F,
    NOTE_SYM_G
]
