
ACCIDENTAL_SHARP = '#'
ACCIDENTAL_FLAT = 'b'

DURATION_WHOLE = 1
DURATION_HALF = 2
DURATION_QUARTER = 4
DURATION_EIGHTH = 8
DURATION_SIXTEENTH = 16
DURATION_THIRTYSECOND = 32

OCTAVE_MIN = 1
OCTAVE_MAX = 8
STRUCTURE_SEPARATOR = '-'

SEPARATOR = ' '

VALID_DURATIONS = [1, 2, 4, 8, 16, 32]
VALID_NOTES = 'ABCDEFG'
VALID_STRUCTURE_LENGTHS = [2, 3]
VALID_ADDITIONALS = 'S.<>@'