
ACCIDENTAL_FLAT = 'b'
ACCIDENTAL_SHARP = '#'

ADDITIONAL_DOTTED_NOTE = '.'
ADDITIONAL_FERMATA = '@'
ADDITIONAL_STACCATO = 's'
ADDITIONAL_SLUR_BEGIN = '<'
ADDITIONAL_SLUR_END = '>'

DURATION_WHOLE = 1
DURATION_HALF = 2
DURATION_QUARTER = 4
DURATION_EIGHTH = 8
DURATION_SIXTEENTH = 16
DURATION_THIRTYSECOND = 32

NOTE_IDX_SYMBOL = 0
NOTE_IDX_ACCIDENTAL = 1
NOTE_IDX_OCTAVE_SHORT = 1
NOTE_IDX_OCTAVE_LONG = 2
NOTE_LEN_SHORT = 2
NOTE_LEN_LONG = 3

NOTE_STRUCTURE_IDX_NOTE = 0
NOTE_STRUCTURE_IDX_DURATION = 1
NOTE_STRUCTURE_IDX_ADDITIONALS = 2
NOTE_STRUCTURE_LEN_SHORT = 2
NOTE_STRUCTURE_LEN_LONG = 3

OCTAVE_MIN = 1
OCTAVE_MAX = 8

BREAK_STRUCTURE_LEN = 2

SEPARATOR_BREAK = '-'
SEPARATOR_NOTE_STRUCTURE = '-'
SEPARATOR_NOTE = ' '

SYMBOL_A = 'A'
SYMBOL_B = 'B'
SYMBOL_C = 'C'
SYMBOL_D = 'D'
SYMBOL_E = 'E'
SYMBOL_F = 'F'
SYMBOL_G = 'G'
SYMBOL_BREAK = '*'

VALID_ADDITIONALS = [
    ADDITIONAL_DOTTED_NOTE,
    ADDITIONAL_STACCATO,
    ADDITIONAL_SLUR_BEGIN,
    ADDITIONAL_SLUR_END,
    ADDITIONAL_FERMATA
]
VALID_DURATIONS = [
    DURATION_WHOLE,
    DURATION_HALF,
    DURATION_QUARTER,
    DURATION_EIGHTH,
    DURATION_SIXTEENTH,
    DURATION_THIRTYSECOND
]
VALID_STRUCTURE_LENGTHS = [NOTE_STRUCTURE_LEN_SHORT, NOTE_STRUCTURE_LEN_LONG]
VALID_SYMBOLS = [
    SYMBOL_A,
    SYMBOL_B,
    SYMBOL_C,
    SYMBOL_D,
    SYMBOL_E,
    SYMBOL_F,
    SYMBOL_G
]
