FIELD_BPM = 'BPM'
FIELD_SKIPBARS = 'skip'
FIELD_TIMESIG = 'tsig'

FIELD_SEP = ','
FIELD_SEP_TIMESIG = '/'
FIELD_SEP_VAL = '='

VALID_FIELDS = [
    FIELD_BPM,
    FIELD_TIMESIG,
    FIELD_SKIPBARS
]

BPM_MIN = 64