KEY_ANACRUSIS = 'anacrusis'
KEY_BPM = 'BPM'
KEY_SKIPBARS = 'skipbars'
KEY_TIMESIG = 'tsig'

SEP_FIELD = ','
SEP_VAL_BPM = '/'
SEP_VAL_TIMESIG = '/'
SEP_KEYVAL = '='

EXPLEN_KEYVAL = 2
EXPLEN_BPM = 2
EXPLEN_TIMESIG = 2

ANACRUSIS_VAL_TRUE = "True"
ANACRUSIS_VAL_FALSE = "Flase"

BPM_VAL_BEAT_VALUE_DOTTED_NOTE = '.'

VALID_KEYS = [
    KEY_ANACRUSIS,
    KEY_BPM,
    KEY_TIMESIG,
    KEY_SKIPBARS
]

VALID_ANACRUSIS_VALUES = [
    ANACRUSIS_VAL_TRUE,
    ANACRUSIS_VAL_FALSE
]

from .notes import VALID_DURATIONS
VALID_TIMESIG_BOTTOM_VALUES = VALID_DURATIONS
VALID_BPM_BEAT_VALUES = VALID_DURATIONS