
BAR_OPEN = '['
BAR_CLOSE = ']'
SETTING_OPEN = '{'
SETTING_CLOSE = '}'

NOTE_ACCIDENTAL_SHARP = '#'
NOTE_ACCIDENTAL_FLAT = 'b'
# NOTE_DURATION_WHOLE = 1
# NOTE_DURATION_HALF = 2
# NOTE_DURATION_QUARTER = 4
# NOTE_DURATION_EIGHTH = 8
# NOTE_DURATION_SIXTEENTH = 16
# NOTE_DURATION_THIRTYSECOND = 32
NOTE_OCTAVE_MIN = 1
NOTE_OCTAVE_MAX = 8
NOTE_STRUCTURE_SEPARATOR = '-'
NOTE_SEPARATOR = ' '
NOTE_VALID_DURATIONS = [1, 2, 4, 8, 16, 32]
NOTE_VALID_NOTES = 'ABCDEFG'
NOTE_VALID_STRUCTURE_LENGTHS = [2, 3]
NOTE_VALID_ADDITIONALS = 'S.<>@'